.vscode/settings.json
The format on save functionality currently causes a heavy amount of modifications due to the files not being formatted properly.
A full clean-up will be done in #193 in a separate milestone.
=> Disable format on save temporarily

.dockerignore, .github/workflows/dev.yml, .github/workflows/main.yml, Dockerfile, bin/copy-trilium.sh, package.json, webpack.config.ts
Adapts the existing build scripts to be able to run with the TypeScript integration, and adds GitHub Actions to build these versions automatically whenever a PR is merged in `develop`.
Here's how it looks like:
The artifacts can be downloaded by scrolling all the way down in the [Run summary page](https://github.com/TriliumNext/Notes/actions/runs/9922994246):
=> Fix build scripts & add CI for running them

README-ZH_CN.md, README.it.md, README.ja.md, README.md, README.ru.md
Addresses issue #191 
I will open another issue to ask speakers of Chinese, Japanese, Russian, and Italian to translate the added portions of "Why Trilium Next" and other small bits added to the forked readme
=> Fixed links to wiki and documentation to redirect to TriliumNext Docs

README.md
The link to the official Docker images is hidden a bit deep inside the documentation, and I think it would make sense to establish the link directly from the README. It's the first I look on projects where I can find related Docker images.
=> docs: Add Dockerhub link to readme

.github/workflows/main-docker.yml, Dockerfile, start-docker.sh
There are quite a few bugs when using GitHub Actions along with `node:alpine` and `armv7`/`armv6` builds. This includes the following issues:
https://github.com/docker/build-push-action/issues/1071
https://github.com/docker/build-push-action/issues/977
https://github.com/nodejs/docker-node/issues/2077
I also tried some of the workarounds listed in the above issues, but instead got really strange errors:
```
docker run testingnotes
No USER_UID specified, leaving 1000
No USER_GID specified, leaving 1000
(node:1) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Generated session secret
#
#
#
#
#FailureMessage Object: 0x7ffc01003cf0
----- Native stack trace -----
```
I …
=> Fix ARM container builds

bin/build-docker.sh, start-docker.sh
Update start-docker.sh to be more distro-agnostic.
Also update `build-docker.sh` to use `triliumnext/notes` instead of `zadam/trilium` for the tags it creates.
=> Update start-docker.sh to be more distro-agnostic

.github/workflows/main-docker.yml
The system to tag concurrent builds is simply just too finnicky right now, and isn't worth it. This change reverts it back to a sequential pipeline.
The other change in here is that `linux/arm64/v8` is normalized as `linux/arm64` currently within Docker.
=> Remove the strategy matrix for concurrent builds.

.github/workflows/main-docker-alpine.yml, .github/workflows/main-docker.yml, Dockerfile-alpine, Dockerfile.alpine
Modified the CI/CD again, to have Debian be for ARM, and Alpine be for AMD64.
=> Alpine = AMD64, Debian = ARM

src/public/app/widgets/find.js
When finding, if you delete a find result in the note and then click to find the next one, an error will occur:
```
CKEditorError: mapping-model-position-view-parent-not-found {"modelPosition":{"root":"$graveyard","path":[0],"stickiness":"toNext"}}
Read more: https://ckeditor.com/docs/ckeditor5/latest/support/error-codes.html#error-mapping-model-position-view-parent-not-found
at Nc.on.priority (<anonymous>:6:643867)
at Nc.fire (<anonymous>:6:470940)
at Nc.toViewPosition (<anonymous>:6:646343)
at Nc.toViewRange (<anonymous>:6:646082)
at n_.<anonymous> (<anonymous>:6:1032187)
at m (<anonymous>:6:602325)
at f (<anonymous>:6:602550)
at p (<anonymous>:6:602439)
```
This pr makes it necessary to update the find results after modifying a note and then clicking on Find Previous and Next.
=> Fix a bug of find widget

src/public/translations/es/translation.json
Addressing https://github.com/TriliumNext/Notes/pull/359#issuecomment-2323208797
Thanks for the notice.
Also noticed that my script replaced strings twice when the replacement should have be done only on the sub-string between `: "` and `"` :sweat_smile:
=> Update Spanish translation

.vscode/settings.json, src/www.ts
In the commit https://github.com/TriliumNext/Notes/commit/40651e985245bfaf4ae1e0e2bfc9d8b233bbc78a which improves error logging, an error message appears when clicking on the desktop shortcut, right-clicking on the taskbar icon, or selecting "New Window" from the taskbar if an Electron instance is already running. However, at this point, the port is already occupied. In the Electron version, it should simply focus on the main window without displaying an error message.
=> The new instance makes the dialog box error not display

src/public/app/services/i18n.js
Let i18n fall back to English for untranslated text to avoid displaying it as blank:
=> i18n Fallback to English for null characters

.github/workflows/main-docker.yml
Suggested as a fix [here](https://github.com/docker/build-push-action/issues/687#issuecomment-1651816012) for our issue [here](https://github.com/TriliumNext/Notes/actions/runs/10835704275/job/30068384041#step:9:276). Otherwise, we may have to take a look at what is enabled in the repository [here](https://github.com/docker/build-push-action/issues/687#issuecomment-1238980158), or give [this](https://github.com/orgs/community/discussions/26274#discussioncomment-3251137) a shot.
=> Add explicit permissions for GITHUB_TOKEN for package access

src/public/app/widgets/buttons/global_menu.js
`e.stopPropagation();` is preventing when click on `Advanced` to close the global menu, but it also prevent it's submenu buttons. Adding conditions to only take effect when click on `Advanced` button.
=> Fix global menu advanced command can't click

.github/workflows/main-docker.yml
Working run, as an example:
https://github.com/perfectra1n/Notes/actions/runs/10865026813/job/30150992278#step:13:10
=> Print Docker container log, regardless of success or failure of healthcheck

README-ZH_CN.md, README.es.md, README.it.md, README.ja.md, README.md, README.ru.md
Current README on `develop` gives 404 error when clicking Spanish link.
=> docs: Use relative link to other README files

src/public/translations/es/translation.json
Some fixes were done thanks by using PO file with [Poedit](https://poedit.net/). It enhances a lot the workflow for translators. Previously using Neovim to translate was somewhat painful 🤪.
---
In order to easy the process to find the missing strings on alredy-translated JSON files I made a small script to create a `PO` file to translate it using Poedit, it tells you of minor issues like extra final point, case dfferences, etc.
The script could be the base for a sane workflow, maybe creating a `Makefile` or something like that.
```shell
#!/usr/bin/env bash
#
#
#
#
#
locales=(cn es ro)
for locale in "${locales[@]}"; do
json2po -t en "${locale}" "po-${locale}"
done
for locale in "${locales[@]}"; do
jq -s '.[0] * .[1]' en/translation.json "${locale}"/translation.json >merged.json
mv …
```
=> i18n: Continue Spanish translation, parts 3 and 4

src/public/stylesheets/style.css
This change overrides the z-index of Bootstrap tooltips (calculates to 1080 in the current version) to the value assigned to CKEditor Panel Balloons (calculates to 1000 in the current version) minus 1. It also removes the original override to the CKEditor Panel Balloons which forces the autocomplete box to appear above tooltips, which is no longer needed and would interfere with math preview boxes.
This change fixes the regression to the [original issue][1] and the [math preview issue][2]. One notable effect is that tooltips will not cover menus when overlapped with one, including menus opened from the top-right corner. Not sure if it is considered normal or not.
Fixes #297.
[1]: https://github.com/zadam/trilium/issues/1272
[2]: https://github.com/TriliumNext/Notes/issues/297
=> Override the z-index of Bootstrap tooltips

src/services/import/zip.ts
Closes #456. Let me know if you're not okay with the type assertion / cast.
=> Resolve MIME type not being used when creating new note correctly, upon zip import

src/public/app/menus/image_context_menu.js
Currently, when right clicking on an image and using "Copy image to clipboard" and then pasting the image in another application (like Trilium running in the web browser) has it paste a broken image. This is the context menu in question:
And this is what it shows when pasting the above image into Trilium running in the browser:
These changes change the context menu from using `copyImageAt` to electron's `clipboard`, and fix the above scenario.
=> Use the electron Clipboard module when using "Copy image to clipboard"

.gitignore, bin/translation.sh, src/public/translations/es/translation.json
The same idea I mentioned on #449
```shell
$  ./bin/translation.sh
Description:
Create PO files to make easier the labor of translation
Usage:
./translation.sh [--stats] [--update <OPT_LOCALE>] [--update2 <OPT_LOCALE>]
Flags:
--clear
Clear all po-* directories
--stats
Print the number of existing strings on the JSON files for each locale
--update <LOCALE>
Update PO files from English and localized JSON files as source
--update2 <LOCALE>
Recover translation from PO files to localized JSON files
```
=> Continue Spanish translation

.github/workflows/main-docker.yml
=> Introduce `stable` tag on containers

src/public/app/components/tab_manager.js, src/public/app/widgets/tab_row.js, src/public/translations/en/translation.json, src/public/translations/ro/translation.json
=> close right tabs

src/services/export/zip.ts
Related to https://github.com/TriliumNext/Notes/issues/528.
Besides that, it feels a bit short to set the maximum length of fileName to 30, as _canvas-export.svg already has a length of 18.
=>  Crop fileName  and prevent cutting into the extension.

.github/workflows/main-docker.yml
Explicitly manage the "latest" tag, and have it point to the same tag as "stable"
=> Explicitly manage the "latest" tag, and have it point to the same tag as "stable"

src/public/app/services/utils.js, src/public/app/widgets/buttons/global_menu.js, src/public/app/widgets/buttons/update_available.js
Continuation of #554, replacing it.
=> More reliably check for version updates

src/public/app/widgets/type_widgets/options/text_notes/editor.js, src/public/translations/en/translation.json, src/public/translations/es/translation.json, src/public/translations/ro/translation.json
Using two radio buttons instead of a combo box is preferable for this case.
=> Replace the editor type combo box with radio buttons

src/public/app/widgets/buttons/attachments_actions.js, src/public/app/widgets/buttons/note_actions.js
Related to https://github.com/TriliumNext/Notes/issues/606
=>  Add box icons to note menu

src/public/app/components/tab_manager.js, src/public/app/widgets/tab_row.js, src/public/translations/en/translation.json
1. Add `reopen_last_tab`: `CTRL+Shift+T` might not be widely known
2. Add `copy_tab_to_new_window`: Sometimes, users might not want to close the original tab in the current window
3. `bxs-x-circle` => `bx-x`: To be consistent with the ico of `.note-tab-close`
=> Add "Reopen last tab" and "Copy tab to new window" to tab management

src/public/app/services/promoted_attribute_definition_parser.js, src/public/app/widgets/attribute_widgets/attribute_detail.js, src/public/app/widgets/ribbon_widgets/promoted_attributes.js, src/public/translations/cn/translation.json, src/public/translations/de/translation.json, src/public/translations/en/translation.json, src/public/translations/es/translation.json, src/public/translations/fr/translation.json, src/public/translations/ro/translation.json, src/services/promoted_attribute_definition_parser.ts
This adds a label definition type for "Time", following the existing "Date" and "Date & Time".
Screenshots:
=> Add label definition type for standalone time

src/public/app/widgets/type_widgets/content/backend_log.js
This hides the resizer since it wasn't working (and isn't necessary).
=> Remove resizer from backend log text area

src/public/app/widgets/note_map.js
Hey guys,
i like the graph view and the force Graph library. Therefore i tried to improve trilium a little bit. Here are some new features:
1. Highlight links and connected nodes when hovering over a node
2. Click on the icon in the middle. It turns red to drag nodes to new locations. The nodes will stay fixed.
3. Slider to change the link distance. 
I appreciate any feedback. It´s my first code contribution to an open source project
=> New Features for note map

src/services/search/expressions/note_content_fulltext.ts
=> Bugfix, Canvas and Mindmap content didn´t show in search

src/public/app/utils/formatters.js, src/public/app/widgets/dialogs/about.js, src/public/app/widgets/dialogs/recent_changes.js, src/public/app/widgets/ribbon_widgets/note_info_widget.js, src/public/app/widgets/type_widgets/options/backup.js, src/public/app/widgets/type_widgets/options/etapi.js
Format dates and times according to the current system/browser's locale.
=> Format dates and times

src/public/app/services/link.js, src/public/app/services/tree.js, src/public/stylesheets/theme-next.css, src/public/stylesheets/theme-next/shell.css
Format the note paths in a more stylish way.
=> Format note paths

src/public/stylesheets/theme-next/shell.css
Note: the restyling is partial. The style of the footer button and the search box buttons will be completed in future.
=> Style Next: Restyle the "Jump to Note" dialog

src/public/app/widgets/dialogs/bulk_actions.js, src/public/app/widgets/dialogs/delete_notes.js, src/public/app/widgets/dialogs/protected_session_password.js, src/public/app/widgets/dialogs/sort_child_notes.js, src/public/app/widgets/type_widgets/options/appearance/code_block.js, src/public/app/widgets/type_widgets/options/appearance/electron_integration.js, src/public/app/widgets/type_widgets/options/appearance/fonts.js, src/public/app/widgets/type_widgets/options/appearance/i18n.js, src/public/app/widgets/type_widgets/options/appearance/max_content_width.js, src/public/app/widgets/type_widgets/options/appearance/theme.js, src/public/app/widgets/type_widgets/options/code_notes/code_auto_read_only_size.js, src/public/app/widgets/type_widgets/options/other/search_engine.js, src/public/app/widgets/type_widgets/options/password.js, src/public/app/widgets/type_widgets/options/spellcheck.js, src/public/app/widgets/type_widgets/options/sync.js, src/public/app/widgets/type_widgets/options/text_notes/text_auto_read_only_size.js
Hi,
this PR ads an explicitly associated label to input elements that did not have one previously (I hope I found all of them :-))
This closes #790.
In a separate PR I will continue working on turning the implicit labels into explicits ones as well, as they usually seem to work better with screen readers, from what I've read online.
=> feat(a11y): explicitly associate label and input elements

src/services/notes.ts, translations/en/server.json
Hello,
This PR makes the "(dup)" suffix for duplicated notes translatable.
Previously this was fully hardcoded as " (dup)", now we can translate it, using `notes.duplicate-note-suffix`.
I've also added support for RTL languages by allowing the translators to decide where the suffix should be placed:
For LTR languages it will be at the "right end" of the string, for RTL languages it will be at the "left end" of the string.
This is using `notes.duplicate-note-title`.
To keep the same functionality as before for RTL langs (where the suffix is only added once for a note, even if there are several clones), I expanded the `res.note.title` check to also check for `startsWith`.
Since majority of languages are LTR, I've kept the "endsWith" check as first check, so that we can make use of …
=> i18n: make duplicate notes suffix translatable

src/public/app/widgets/type_widgets/options/backup.js, src/public/translations/cn/translation.json, src/public/translations/de/translation.json, src/public/translations/en/translation.json, src/public/translations/es/translation.json, src/public/translations/fr/translation.json, src/public/translations/ro/translation.json, src/public/translations/tw/translation.json
Hello,
this PR improves translatability of the `backup.database_backed_up_to` message by moving the backupFile path into the translation string – this a) makes the string RTL translatable and b) adds more context for LTR languages as well.
=> i18n: improve translatability of database_backed_up_to string

src/public/app/widgets/dialogs/protected_session_password.js
I've accidentally introduced those 4 letters at the end of the string, with my last commit :-)
Sorry!
=> chore: fix typo in protected_session_password dialog

src/services/session_secret.ts
Hi,
this PR repalces the `randomValueHex` function (which is not used anywhere else across the codebase) with the already existing `randomSecureToken` function from the utils module for the creation of the session.
They both are using the `randomBytes` method of the crypto module.
This also improves secret security, as `randomSecureToken` uses Base64 and hence a much larger charset size than `randomValueHex` (which also unnecessarily was made even a bit more insecure, by having all characters UPPERCASED, so an even smaller charset size).
Some examples:
```
$ for i in $(<hashB64.txt); do echo "$i | $(echo $i | ent | head -1)"; done
XkPHvfhZISIS0OsfO6TzRbQkSdnTNLUZ0r+1qu9TD0CEm17isJ21tYUY5QjD/q7P | Entropy = 5.329759 bits per byte. …
```
=> refactor(session_secret): use existing randomSecureToken function

src/services/attributes.ts, src/services/search/expressions/note_content_fulltext.ts, src/services/search/services/parse.ts, src/services/utils.ts
Hi,
this PR aims to replace a handful of lookups via Array's `include` method with lookups via Set's `has` method.
These are a lot faster, as the `include` method is doing a linear search, whereas Set's `has` implementation is a hash table or a search tree according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) (I guess it depends on the used JavaScript runtime)
I did some very basic benchmark ( I can provide the code if desired) and got the following results for a 1000 test runs of the "worst case" for Arrays (i.e. the value that we are looking for is at the end of the Array):
```
Suite: Compare Set 'has' vs Array 'includes'
============================================
✔ Set has '%=           217.347.485 ops/sec
✔ Array includes '%=' …
```
=> refactor(services): use Set instead of Arrays for faster lookups

spec-es6/sanitize_attribute_name.spec.ts, src/becca/entities/battribute.ts, src/routes/api/sender.ts, src/services/consistency_checks.ts, src/services/import/enex.ts, src/services/sanitize_attribute_name.ts
Hi,
I've simplified the sanitizeAttributeNames function and updated the way it gets exported: there is no need to have the function wrapped in an object, just export it directly and save some typing :-)
I also created a very basic test/spec file using the provided test runner.
=> refactor(sanitizeAttributeName): simplify function and export

src/services/keyboard_actions.ts, src/services/log.ts, src/services/options_init.ts, src/services/utils.ts, src/services/window.ts
Hi,
this PR aims to consolidate isMac and isWindows functions into single central functions in utils, so that there is only place that needs to be maintained in the future.
(Addmittedly: it of course will be unlikely that the process.platform values will change very soon, but this still makes it a bit cleaner than having several `process.platform === "` comparisons across the codebase).
I only did this on the server side of things, I did not touch the "frontend" part, which already contains its own isMac function in its utils module
=> refactor(utils): add isMac and isWindows util functions

spec-es6/utils/formatDownloadTitle.spec.ts, src/services/utils.ts
Hi,
this PR aims to make the `formatDownloadTitle` function a tiny bit easier to read and hopefully maintain, with basic tests added, to make sure nothing breaks.
I've refactored the code to separate the process of determining the file extension from the rest, so it looks less nested, and reused some mimeType built-in functions to make things easier.
Regarding the test:
Unfortunately `tsx` does not seem to like running the tests (using `npx tsx -r esm spec-es6/utils/formatDownloadTitle.spec.ts`), even though `npx tsc` does not complain about any errors.
With node's TS runner (using `node  --experimental-transform-types spec-es6/utils/formatDownloadTitle.spec.ts`) it did run, but only after changing the "env.js" import to "env.ts".
I'll need to do some additional investigation on this, but …
=> refactor(utils/formatDownloadTitle): simplify function

package-lock.json, package.json, spec/support/etapi.ts
Hi,
this removes the now unused `tree-kill` dependency.
The code that used it got removed with commit e393914,
but seems that the dependency remained as leftover.
=> chore(deps): remove unused tree-kill dependency

src/public/app/services/link.ts, src/services/html_sanitizer.ts
These changes add support for geo-URIs as described in [RFC 5870](https://www.rfc-editor.org/rfc/rfc5870).  
To take effect, they depend on a second pull request for [TriliumNext/trilium-ckeditor5](https://github.com/TriliumNext/trilium-ckeditor5): [here](https://github.com/TriliumNext/trilium-ckeditor5/pull/3).
Geo-URIs are mostly handled by the OS so I implemented them similar to the file-scheme. GNOME on Linux and Android both offer out-of-the-box support for geo-URIs. Others need third-party apps.  
Geo-URIs are handy for referencing locations in notes.
=> Added support for RFC 5870 geo-URIs

src/views/login.ejs
Hi,
this PR aims to get rid of "FOUC" aka "Flash of unstyled content" that appears on the login page.
This is noticeable, if you go to the login page and reload the page – for a fraction of a second you will see the content go from unstyled to its final styled version.
Fix is easy: Stylesheets should be linked in the head, rather than the bottom of the HTML files.
=> fix(views/login): fix "flash of unstyled content"

src/views/set_password.ejs, translations/cn/server.json, translations/de/server.json, translations/en/server.json, translations/es/server.json, translations/fr/server.json, translations/pt_br/server.json, translations/ro/server.json, translations/tw/server.json
Hi,
this PR fixes some tiny things in the `set_password` view (see commit messages).
Regarding the `set_password.title` comment I made in the one commit message:
Currently the title is just showing "Set Password", without any hint that this is a TriliumNext page (except for the favicon).
E.g. the "main" view is showing the page title as "${Note Title} - TriliumNext Notes", which makes it easy to spot.
I'll work on this on a separate PR though.
=> fix(views/set_password): various smaller fixes

src/routes/index.ts, src/views/desktop.ejs, src/views/mobile.ejs, src/views/partials/windowGlobal.ejs
Hi,
this PR aims to reduce code duplication, by using an ejs partial for injecting the window.glob part.
Now we only have to take care of it in one single place :-)
=> refactor(views): use ejs partial for injecting window.glob

.prettierignore, package-lock.json, package.json
Hi,
I found a `.prettierrc` file in the root of the folder, which got added via https://github.com/TriliumNext/Notes/pull/165
However I did not find it in the devDependencies.
I've added it as devDep and added two basic scripts to run prettier and I added an initial `.prettierignore` – this one might need some tweaking still.
The prettier check shows more than 600 files that would need "editing" – but that is not part of this PR.
=> chore(prettier): add prettier as devDep and scripts

.prettierrc
Hi,
I've added an override section for json files, to match the tab width to the "indent_size" value from the `.editorconfig`.
=> chore(prettier): add override for *.json tab width to match .editorconfig

src/public/stylesheets/print.css
Hi,
this PR aims to fix #901. As per comment https://github.com/TriliumNext/Notes/issues/901#issuecomment-2579632456 I  did not add all of the styles, but instead had to add a "workaround" for `print.css`.
The main issue here is that browsers will strip all background colors when printing, and the input checkboxes coming from ck-editor unfortunately all use custom styling, which involves setting the background (e.g. to green) and the color of the checkmark to white.
After the browser strips the background color, the checkmark is still there, but it is "white on white", which makes it invisible.
A bit "hack-ish" solution, which works well enough though:
we set the input's border to half the size of the input element to create a fake background, that the browser will not strip out, when you …
=> fix(styles): fix ck-editor checkboxes not showing checkmark while printing

package.json
Hi,
I've added `npx playwright test` as script to the `package.json` as `test-playwright`.
Admittedly `npm run test-playwright` is not really shorter than `npx playwright test`, BUT having in explicitly shown under "scripts" shows everyone at a quick glance, that playwright is being used for tests here.
=> chore(scripts): add `test-playwright` script to package.json

src/public/app/widgets/type_widgets/editable_text.js
For #454 and #831, it would be useful to have logging about the state of the CKEditor in the server logs. This could help give us better understanding of frontend crashes, and other weird frontend state.
=> Add server logging for CKEditor state changes

spec-es6/data_dir.spec.ts, src/services/data_dir.ts
Hi,
this PR aims to refactor the `data_dir.ts` file.
- make code more DRY, reducing duplicate code
- switch to using path.join instead of manual path concatenation using path.sep
- reordered logic in the `getTriliumDataDir` function to be more easy to follow the order of "trilium data path order of priority"
- added tests for these functions (except for getTriliumDataDir -> see below please)
- replacing previously exported values with a proper readonly object, that is now also testable
regarding the `getTriliumDataDir` tests:
since this function is also using `fs` related methods (i.e. checking for folder existance and folder creation), I have to ways on how to make the function testable:
a) using a simple DI object, to "inject" these dependencies (`fs` methods, etc.) which will allow to …
=> refactor(data_dir): simplify logic and make code robust and testable

src/routes/api/backend_log.ts, translations/de/server.json, translations/en/server.json
Hi
this PR aims to improve the `getBackendLog` function in the `backend_log` route:
most notable:
- I've replaced the synchronous reading of the file with an async reading, which makes more sense for a backend api function
- error handling is more user friendly, as they get back an actual message instead of just an empty string
=> refactor(backend_log): improve `getBackendLog`

package.json
Hi,
this PR updates the `start-test-server` script
- switches to nodemon
- chains commands with `&&` instead of `;` so that it'll only run subsequent commands, if the previous one was succesful
The previously used `ts-node` was not even working with the `start-test-server` script anymore, it was throwing an error like "Unknown file extension for main.ts"
=> chore(scripts): update `start-test-server` script

src/views/desktop.ejs, src/views/mobile.ejs
Hi,
Chrome was throwing a warning at me recently
This PR fixes that, it also was already implemented by e.g. Flutter or vercel/Next.js, so we should be OK here ;-)
https://github.com/vercel/next.js/pull/70363
https://github.com/flutter/flutter/issues/154596
=> fix(views): replace deprecated meta tag

src/routes/csrf_protection.ts, src/routes/index.ts, src/routes/routes.ts
Hi,
this PR changes the way the `_csrf` cookie is being handled during generation.
I've switched over from using the `req.csrf` method (which get's added *after* the request passes the csrfMiddleWare) to explicitly using `doubleCsrf`'s `generateToken` method.
This allows us to change the parameters (a bit more easily and without any typing issues) as per below:
//'overwrite' set to false (default) => the existing token will be re-used and validated
//'validateOnReuse' set to false => if validation fails, generate a new token instead of throwing an error
See https://www.npmjs.com/package/csrf-csrf under "generateToken" for further info.
While I as at it, I've refactored the csrf_protection to its own file, for better separation, similar to what was done with the session_parser middleware. …
=> fix(csrf): fix handling of existing _csrf cookies

src/routes/csrf_protection.ts, src/routes/index.ts
Hi,
this PR sets some more "secure" settings for csrf.
As per OWASP:
"A CSRF token must not be leaked in the server logs or in the URL.", see:
https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#transmissing-csrf-tokens-in-synchronized-patterns
- `sameSite` - previous setting inherited from csurf was to simply not set it at all (i.e. "none"), which makes all browser nag in their dev console output.
They will default to "Lax" for these type of cookies in the future.
We can even use "strict" here though for our use case without an issue:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#samesitesamesite-value
- `httpOnly`: should be enabled for the csrf cookie as well
for the session cookie it already is enabled. …
=> fix(csrf): set more secure csrf related settings

src/routes/csrf_protection.ts
Hi,
this PR is "hotfix" for an issue with Electron, that I introduced with https://github.com/TriliumNext/Notes/pull/961
I forgot to rebuild and test the electron version, sorry about that!
Electron it does not seem to like having httpOnly set, which causes the cookie *not* to be sent to the server, and hence csrf failing.
For the web/server version httpOnly is definitely working, tested on localhost and also on a deployed server with proper domain and SSL termination by nginx – httpOnly works without issues there.
Let's add an exception for isElectron for now, and check, if there is a way around it Electron as well :-)
=> fix(csrf): add exception for electron for httpOnly cookie

dump-db/inc/data_key.ts, dump-db/inc/decrypt.ts
The `dump-db` tool appears to be designed for a much older version of Trilium.
Related issue:
https://github.com/zadam/trilium/issues/3017
Referencing this commit:  
[Commit Reference](https://github.com/zadam/trilium/commit/5a37547b37177d81e12532ba02c40e53562c614e)
At that time, the `ivLength` was incorrectly set to 13 instead of the correct value of 16. Consequently, if you attempt to use this tool to decrypt encrypted notes from the current database version, you will encounter errors because the tool's default `ivLength` remains at 13.
Code reference:  
[Source Code Reference](https://github.com/TriliumNext/Notes/blob/7dfeb20678708ecb3d12852c6bac857af1bfd59b/dump-db/inc/decrypt.ts#L19)
Error message:  
`Caught WRONG_FINAL_BLOCK_LENGTH, returning cipherText instead`
To reproduce the …
=> Fix default ivLength in dump-db tool

src/views/share/page.ejs
navigating from a sub note to the parent note when the parent note is the root note is broken due to the missing relative path specifier
href for the parent node if it is the root node is "" instead of "./" see the differing behavior of referencing child nodes
https://github.com/TriliumNext/Notes/blob/b2e1a3e97ad93ba5a0d48fab5444bb42275dce5a/src/views/share/page.ejs#L66-L69
vs the parent node
https://github.com/TriliumNext/Notes/blob/b2e1a3e97ad93ba5a0d48fab5444bb42275dce5a/src/views/share/page.ejs#L38-L40
=> Fix parent share link

spec/search/search.spec.ts
Hi,
I've adjusted message to be printed correctly and adjusted wording to make it more clear, what is actually tested here (the length of results)
-> previously it was printing "[object object]", since we are dealing with an  array of objects
=> test(spec/search): fix expect error message printing

spec-es6/data_dir.spec.ts
Hi,
this PR adds tests for `data_dir`'s `getTriliumDataDir` function.
It ports my previously written "nodejs test runner" based tests (see: bla), to use vitest and integrates them in the same spec file (which required some adjustments to the other tests as well).
=> test(data_dir): add missing getTriliumDataDir tests

src/public/app/services/utils.ts
Hi,
this PR aims to get rid of the Webpack warning that appears when running webpack:
```
WARNING in ./src/public/app/services/utils.ts 249:15-34
Critical dependency: the request of a dependency is an expression
```
It does it by simply explicitly passing the moduleName as string using template literal and not the moduleName "expression",
Source: https://stackoverflow.com/questions/42908116/
=> fix(utils/dynamicRequire): get rid of Webpack Critical dependency warning

src/services/data_dir.spec.ts
Hi,
this PR fixes the one flaky test on Windows for the getPlatformAppDataDir test suite.
=> test(data_dir): fix flaky getPlatformAppDataDir test on Windows

src/services/import/mime.spec.ts, src/services/import/mime.ts
Hi,
this PR adds unit tests for `services/import/mime` and then does some refactoring, to simplify the code a tiny bit.
=> refactor: refactor and add tests for `services/import/mime`

bin/generate_document.ts, package.json
Hi,
this file is never called in production code and wouldn't even run, even if it was:
the `lorem-ipsum` dependency is in the `devDependencies`, so never gets installed in
any dist builds.
I moved the file to "bin" where it makes more sense, where other "like minded" scripts are found.
This way we avoid it getting packaged without any reason.
Apart from that: I've added a comment to the script -> it seems to be broken at the moment – I did not get it to run correctly. see #1020
=> chore: move generate_documents  to bin folder

webpack.config.ts
Hi,
this just simply adds the Configuration Type from webpack to the webpack.config.ts -> allows for intellisense in e.g. VSCode, so makes it a bit easier to work with the file :-)
=> chore(webpack): add Configuration type

src/services/import/utils.spec.ts, src/services/import/utils.ts
Hi,
this PR:
- adds tests for the import/utils.ts 
- and it fixes #1016
=> fix(import/utils.handleH1): fix stripping of all <h1> tags that match title tag

issue_template.md
chore: delete outdated issue_template.md, the current ones are already existing under `.github`
=> chore: delete outdated issue_template.md

.npmrc, package.json
Hi,
this PR removes the default setting of using `legacy-peer-deps` in .npmrc, and instead adds an override section in package.json.
This allows us to handle these peer dependency issues on a case by case basis, instead of generally allowing it for all packages, which could lead to unnoticed issues.
Using  `legacy-peer-deps` is [not recommended  ](https://docs.npmjs.com/cli/v7/using-npm/config#legacy-peer-deps)
In our specific case the `@mind-elixir/node-menu` package is the only package that currently causes peerDep issues, as
it still using mind-elixir 2.x.x as peerDep, which cannot be resolved, since we use v4.
Upstream issue to properly resolve the issue was also created https://github.com/SSShooter/node-menu/issues/4
=> build(npm): use specific overrides instead of `legacy-peer-deps`

Dockerfile, Dockerfile.alpine, bin/copy-trilium.sh, src/public/app/share.ts
Hi,
this PR allows for webpack to take care of the share.js file – without losing the "fetchNote" functionality.
This involves a small "workaround" in the share.js, to avoid Webpack from treating it as dead code – I was trying to get the same result by using webpack config flags, but was not able to get the correct results.
Since we now have webpack taking care of the share.js:
* we can port it to TS (which I did here as well)
* we can get rid of the manual copying of the file in the Dockerfile and the copy-trilium.sh build scripts.
this also should fix #1029
=> chore: make share.js work with webpack

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Let's make use of the type field for the issues:
https://github.com/orgs/community/discussions/148715#discussioncomment-11845050
Since the "bug" and "feature" labels have also been removed, I've removed them from the yml as well :-)
=> chore(issue_templates): Use new type field

src/views/setup.ejs
Hi,
this PR wraps the forms used in the setup.ejs file in an actual "form" tag, so that we can make use of the forms' "submit" event, which is the "standard" way of handling these things usually.
fixes #94
=> fix(setup): make keyboard navigation work

src/app.ts, src/routes/api/clipper.ts, src/routes/api/files.ts, src/routes/assets.ts, src/routes/csrf_protection.ts, src/routes/index.ts, src/routes/routes.ts, src/routes/setup.ts, src/services/app_icon.ts, src/services/app_path.ts, src/services/auth.ts, src/services/code_block_theme.ts, src/services/env.ts, src/services/keyboard_actions.ts, src/services/log.ts, src/services/options_init.ts, src/services/port.ts, src/services/request.ts, src/services/sql_init.ts, src/services/utils.ts, src/services/window.ts, src/services/ws.ts, src/www.ts
Hi,
this PR replaces the  isMac/isWin/isElectron/isDev functions that are returning a boolean.
These values cannot change during runtime under any **normal** circumstances (i.e. the process will never suddenly switch from a "win32" platform to a "darwin" platform midst execution, or the process.env value will not change, unless we do something sketchy during runtime).
→ There is no need to have these checks as functions – instead just do the check once and export and reuse those values directly.
Let's us save some computing power (admittedly it'll be a *very very* tiny bit) ;-)
=> refactor(server/utils): turn isMac/isWin/isElectron/isDev into boolean

libraries/codemirror/eslint.js
not sure why 'latest' is not working, but this fixes the annoying errors related to es5 being default for parsing.
Anything more recent than 2019 does not work unfortunately.
=> Band-Aid fix for the bootleg eslint

src/public/app/services/note_autocomplete.ts
`$el.autocomplete();` will cause full-text search to malfunction. If this line is included, clicking full-text search will result in an error, and the search will not be triggered：
After removing this line of code, clicking full-text search works correctly：
=> Fix a bug in the full text search in AutoComplete

bin/electron-forge/desktop.ejs
Hi,
This PR aims to make the desktop.ejs template that is used for the Linux packages *a lot* easier to read.
We just define the lines as an Array tuple, and then filter out any values, which are falsy (or in this case undefined), before joining them with a "\n" new line.
electron-forge correctly packages the file and its output is identical to the previous template
I admit, this a tiny bit of a useless refactor, but it still irked me to see that file in its previous state :-D
=> refactor(bin/electron-forge): make desktop.ejs easier to read

src/services/import/mime.spec.ts, src/services/import/mime.ts
Hi,
this PR adds some tiny extra handling for ".ts" file which in 2025 are more likely to be TypeScript rather than some older video format.
fixes #1142
=> fix(import/mime): fix ts file mime import handling

src/public/stylesheets/style.css
Hi,
this PR fixes some weird behaviour in dropdown menus:
Currently you were able to select text, by holding the left mouse button and dragging the mouse across the screen, while inside the dropdown menu.
=> fix(ui): disallow text selection in dropdown-menus

config-sample.ini, src/routes/login.ts, src/routes/session_parser.ts, src/services/config.ts
Hi,
this PR is a feature on top of #1155 – which is why you see some extra commits here.
It will allow users to set their own session expiration, e.g. currently it defaults to 1 day – but I can see users who might want to limit it to a shorter period of time (myself included ;-)).
it also set the TTL of the FileStore for the session to the same value as the maxAge from the cookie.
Before that it was set to 30 days, which (if I am not completely mistaken) would've left a couple of dead "unused" session in the FileStore.
~(this still needs some testing "in the field", which is why it is set to draft)~
=> feat: allow setting custom session cookie expiration

package-lock.json, package.json, spec/etapi/app_info.ts, spec/etapi/backup.ts, spec/etapi/import.ts, spec/etapi/notes.ts, spec/support/etapi.ts
Hi,
this removes the types package for jasmine, which I forgot to remove last time :-)
edit: I've also marked the "old" etapi tests as TODO and commented them out for now – they were making Typescript build fail, since we removed the jasmine types.
=> deps: remove leftover @types/jasmine

bin/copy-dist.ts
Hi,
this PR "unpacks" the messages before passing them on to console.log.
Previously it was printing all messages as part of an array, which was unnecessarily ugly/hard to read  i.e. 
```
["message A1"]
["message B1", "message B2"]
```
After spreading the array, we get the actual intended/desired output of
```
message A1
message B1 message B2
```
=> chore(copy-dist): "unpack" log messages before printing

src/becca/entities/bbranch.ts
Mainly to allow unsharing hoisted notes. Closes #518 and #707.
=> Allow removing weak branches even if it's hoisted

src/public/app/widgets/type_widgets/options/other/attachment_erasure_timeout.ts, src/public/app/widgets/type_widgets/options/other/note_erasure_timeout.ts, src/public/app/widgets/type_widgets/options/time_selector.ts, src/public/translations/cn/translation.json, src/public/translations/de/translation.json, src/public/translations/en/translation.json, src/public/translations/es/translation.json, src/public/translations/fr/translation.json, src/public/translations/ro/translation.json, src/public/translations/tw/translation.json, src/routes/api/options.ts, src/services/options_init.ts, src/services/options_interface.ts
Hi,
this PR aims to add a reusable time selector option widget, as an "expansion" of #1163.
It introduces a new class "TimeSelector" that extends the OptionsWidget.
Any option widgets that want to use it are then extending the TimeSelector class.
Embedding the "TimeSelector"'s own widget template is currently done by splitting the widgets TPL where the TimeSelector should appear and using "append" to "inject" the "TimeSelector" template in between.
→ I don't really like this "template concat" solution though, so if you have a better approach let me know.
I was trying out adding an "empty" div with an id and then trying jQuery's `replaceWith` function to inject the TimeSelector widget, but that didn't work for some reason (it would've been a more elegant solution).
The TimeSelector does …
=> feat: add time selector option widget

src/public/app/widgets/type_widgets/geo_map.ts
Small change to the new geomap feature that I thought would improve it a bit. Now the icon that is shown inside the marker uses the color attribute of the note
=> Enhance geomap marker icons with color

src/services/options_init.ts
since it is a very widespread/popular language, it makes sense to have it on by default :-)
closes #1219
=> feat(options_init): add typescript as default set codeNotesMimeTypes value

.github/workflows/release.yml
apply same fix as https://github.com/TriliumNext/Notes/commit/558bee72e929afe6f7471d7557d76a4898d5a18f on release workflow
(I thought there would be an additional issue with the action.yml – because in the old action.yml there was some windows specific Powershell code to rename the files. This isn't here anymore and I thought that would be causing the files to be missing, but it looks like that is not really the case – otherwise the previously fixed nightly workflow would still be missing the files as well).
=> fix(ci): add missing windows zip build target

.github/actions/build-electron/action.yml
Hi,
this removes the now unneeded arm64 workaround
the change is now part of electron-forge 7.7.0 which we depend on since
https://github.com/TriliumNext/Notes/commit/fa05f15753fcbfb38129cb9792a063093798d80b
test build on my fork works fine as well:
https://github.com/pano9000/TriliumNextNotes/actions/runs/13472666704/job/37648069341
=> ci: remove unneeded extra arm64 handling

src/public/app/widgets/buttons/global_menu.ts, src/public/app/widgets/close_zen_button.ts, src/public/translations/en/translation.json
Hi,
this PR fixes two tiny UI issues with the Zen Mode buttons:
a) it now displays the `<kbd>` shortcut in the global menu
b) it adds a short title message to the button element
=> fix/i18n: tiny zen mode UI fixes

tsconfig.webpack.json
Hi,
This fixes the currently broken webpack build, which (on my end) is throwing the following errors due to missing types:
```
ERROR in /home/pano/Programming/0_repos/TriliumNextNotes/src/services/utils.ts
7:21-31
[tsl] ERROR in /home/pano/Programming/0_repos/TriliumNextNotes/src/services/utils.ts(7,22)
TS7016: Could not find a declaration file for module 'unescape'. '/home/pano/Programming/0_repos/TriliumNextNotes/node_modules/unescape/index.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/unescape` if it exists or add a new declaration (.d.ts) file containing `declare module 'unescape';`
ERROR in /home/pano/Programming/0_repos/TriliumNextNotes/src/services/notes.ts
25:27-43
[tsl] ERROR in /home/pano/Programming/0_repos/TriliumNextNotes/src/services/notes.ts(25,28)
TS7016: …
```
=> build(webpack): fix missing type declarations

.github/actions/build-electron/action.yml, .github/workflows/main.yml, .github/workflows/nightly.yml
Unfortunately, in all our pipelines we have to explicitly provide the following environment variables in the step that runs `build-electron`:
```yaml
env:
APPLE_APP_CERTIFICATE_BASE64: ${{ secrets.APPLE_APP_CERTIFICATE_BASE64 }}
APPLE_APP_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_APP_CERTIFICATE_PASSWORD }}
APPLE_INSTALLER_CERTIFICATE_BASE64: ${{ secrets.APPLE_INSTALLER_CERTIFICATE_BASE64 }}
APPLE_INSTALLER_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_INSTALLER_CERTIFICATE_PASSWORD }}
APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
APPLE_ID: ${{ secrets.APPLE_ID }}
APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
```
This is because the `build-electron` step is a `composite` step, and therefore does not have direct access to the repository's `{{ secrets.value }}` GitHub Action's secrets.
=> Pass the required `APPLE` secrets to the `build-electron` action

src/public/translations/en/translation.json, src/routes/index.ts, src/views/desktop.ejs
Previously, `appThemeBase` could only be set to `next`, with the theme automatically switching to dark or light mode based on the system. 
Now, `appThemeBase` can be set directly to `next`, `next-light`, or `next-dark`.
=> Theme use next as base

package.json
Hi
this PR fixes the currently failing electron-forge builds.
This is caused by my recent change, where I had to change the output dir of "build:prepare-dist" from "dist" to "build".
-> this is just a temporary fix to fix building again via CI nightly
-> I am working in parallel already on an improved electron-forge build process, which will be ready by end of the week
=> fix(build/electron): hotfix for failing nightly electron builds

src/public/app/widgets/view_widgets/calendar_view.ts
- rename "promotedAttributes" into "displayedAttributes" and permit non-promoted attributes to be displayed
- make it so that events with customized `calendar:startDate` and `calendar:endDate` can be drag&dropped on the calendar view
=> feat(calendar) improvements

docs/User Guide/User Guide/Advanced Usage/Advanced Showcases/Day Notes.md, src/public/app/doc_notes/en/User Guide/User Guide/Advanced Usage/Advanced Showcases/Day Notes.html, src/services/date_notes.ts
This PR adds the new month pattern ```{isoMonth}```, which is replaced by the ISO 8601 month, such as ```2025-03``` for March 2025.
Trilium automatically creates notes in a year/month/day hierarchy when a new day note is created, typically from the calendar widget. The month note title pattern attribute ```#monthPattern``` defaults to ```{monthNumberPadded} - {month}```. This pattern generates the title "03 - March" for March 2025.
The pattern generates the same title for the month of March in any year. This concise format is easily understood within the context of the note tree, where months appear hierarchically under years (and days under months).
The format is ambiguous when it appears as an internal link within some note text. A reader must mouse over the link to see the full …
=> Add {isoMonth} month pattern to day notes

.github/actions/build-electron/action.yml
Reverts TriliumNext/Notes#1495
Due to https://github.com/Apple-Actions/import-codesign-certs/issues/69.
=> Revert "chore(deps): update apple-actions/import-codesign-certs action to v4"

src/public/app/menus/electron_context_menu.ts
Hi,
this PR aims to fixes bug described in #543  - it was caused by a  wrong check in the "enabled" prop:
It was previously checking if `canPaste` - which in this context does not make sense.
Here it would only make sense to check for `hasText`, which is already done here https://github.com/TriliumNext/Notes/blob/aa418c49a30d18522b63d4b8b1714d1d2dde452f/src/public/app/menus/electron_context_menu.ts#L96
just need to do a quick build and test properly, before I mark this as ready - will happen later today.
fixes #543
=> fix(electron_context_menu): fix disabled search engine contex menu on readonly notes

src/public/app/services/note_autocomplete.ts, src/routes/api/autocomplete.ts, src/routes/api/stats.ts, src/routes/routes.ts
1. https://github.com/TriliumNext/Notes/commit/fd53e35f6fe8a2a82ef8937b7763e9cc9daf9eb3#r154636117
For some languages, such as Chinese, a word may consist of only 1-2 characters, so directly setting a minimum search length might not be applicable to all languages. Therefore, it has been modified to use a delay method to prevent jitter.
2. To avoid triggering a search during character composition.
For example, when the input status of the following figure should not be searched:
=>  To prevent search lag when there are a large number of notes

src/public/app/services/note_autocomplete.ts
When the `compositionend` event is triggered, the character composition by the input method has been completed. However, due to the nature of input methods, the final content in the input box does not always trigger a search.  
For example, in Chinese input methods, if you type "Note" and there are no corresponding Chinese candidates, pressing Enter directly will submit "Note." Since the input box content hasn't changed, the search won't be triggered.  
This PR forces the search to be triggered when the `compositionend` event ends.
=> Forced to trigger search after compositionend

src/services/data_dir.spec.ts, src/services/in_app_help.spec.ts, src/services/sanitize_attribute_name.spec.ts, src/services/tree.spec.ts, src/services/utils.spec.ts, src/share/routes.spec.ts
Hi,
this PR is just running the formatting rules on the .spec files.
This shouldn't affect any open PRs at all.
One thing I did not do here yet: Fix line-length issues from "@stylistic/max-len" rule
=> chore(format): format .spec files

packages/turndown-plugin-gfm/package-lock.json
fixes
3 vulnerabilities (1 high, 2 critical)
```
browserify-sign  2.6.0 - 4.2.1
Severity: high
browserify-sign upper bound check issue in `dsaVerify` leads to a signature forgery attack - https://github.com/advisories/GHSA-x9w5-v3q2-3rhw
fix available via `npm audit fix`
node_modules/browserify-sign
elliptic  <=6.6.0
Severity: critical
Elliptic Uses a Broken or Risky Cryptographic Algorithm - https://github.com/advisories/GHSA-r9p9-mrjm-926w
Elliptic's EDDSA missing signature length check - https://github.com/advisories/GHSA-f7q4-pwc6-w24p
Elliptic's ECDSA missing check for whether leading bit of r and s is zero - https://github.com/advisories/GHSA-977x-g7h5-7qgw
Elliptic allows BER-encoded signatures - https://github.com/advisories/GHSA-49q7-c7j4-3p7m
Signature Malleabillity in elliptic …
```
=> fix(turndown-plugin-gfm): run npm audit fix

src/routes/api/recovery_codes.ts, src/services/encryption/recovery_codes.ts, src/services/sql.ts
Explicitly cast return value as type variable T, so that it gets used.
Previously the type variable was useless, because
the returned variable `const ret = (dbConnection.transaction(func) as any).deferred();` was inferred as "any" by TS, so "T" was never really used.
=> types: use type variable for sql.transactional's return value

src/services/auth.ts
=> fix(auth): avoid "Error: Option 'redirectBareDomain' doesn't exist" on new installations

src/routes/login.ts
send back 401 on failed login, same as we did before TOTP:
https://github.com/TriliumNext/Notes/blob/62706a6af2a7ffa3c7411e5ecbd9ce865ecc6049/src/routes/login.ts#L67
closes #1707
=> fix(login): send back 401 Unauthorized on failed login attempt

src/services/etapi_tokens.ts
This PR adds Bearer authentication for ETAPI and solves #1701.
With ETAPI token, now you can use perform REST calls:
```
GET https://myserver.com/etapi/app-info
Authorization: Bearer ETAPITOKEN
```
This is equivalent to
```
GET https://myserver.com/etapi/app-info
Authorization: ETAPITOKEN
```
=> Support Bearer Authentication

src/public/app/services/link.ts, src/public/app/widgets/ribbon_widgets/note_paths.ts
1. Make each part of the note path in the ribbon clickable, allowing users to navigate to parent notes via the ribbon. Also fixed the issue where its CSS was not applied correctly.  
before:
after:
2. Enable Ctrl + Shift + Click to open a note in a new tab and activate it, aligning the interaction with Firefox and Edge behavior.
=> Make each part of the note path clickable.
