package-lock.json, package.json, src/app.js, src/becca/becca-interface.ts, src/routes/api/attributes.ts, src/routes/api/files.ts, src/routes/api/image.ts, src/routes/api/import.ts, src/routes/api/login.ts, src/routes/api/sender.ts, src/routes/assets.ts, src/routes/custom.ts, src/routes/electron.ts, src/routes/error_handlers.ts, src/routes/index.ts, src/routes/login.ts, src/routes/route-interface.ts, src/routes/routes.js, src/routes/session_parser.ts, src/routes/setup.ts, src/services/auth.ts, src/services/backend_script_api_interface.ts, src/services/import/opml.ts, src/services/import/zip.ts, src/services/script.ts, src/services/session_secret.ts
Language|files|blank|comment|code
:-------|-------:|-------:|-------:|-------:
TypeScript|191|5032|1463|19492
JavaScript|56|1183|324|4448
--------|--------|--------|--------|--------
SUM:|247|6215|1787|23940
=> Convert backend to TypeScript (80% -> 81%) 

README.md
Add "unofficial" section, and add some fancier wording around "discuss with us"
=> Add "unofficial" section, and add some fancier wording

src/services/import/single.ts
=> Unable to import a PDF file

package-lock.json, src/etapi/attachments.ts, src/etapi/attributes.ts, src/etapi/etapi-interface.ts, src/etapi/etapi_utils.ts, src/etapi/notes.ts, src/share/shaca/entities/rows.ts, src/share/shaca/entities/sattachment.ts, src/share/shaca/entities/sattribute.ts, src/share/shaca/entities/sbranch.ts, src/share/shaca/entities/snote.ts, src/share/shaca/shaca_loader.ts, tsconfig.json
=> Update TypeScript dependencies

.gitignore
Ignore JetBrains IDE shelf files, e.g. git stash files
=> Ignore JetBrains IDE shelf files

src/public/translations/es/translation.json
Is this the only file that needs to be translated?
There could be some strings that would need minor fixes but need to hear from fellow Spanish speakers to see what they think.
=> i18n: Add Spanish translation

src/services/window.ts
Create a new window from the taskbar. Tests fine on windows 11.
=> Open New window from taskbar

README.es.md, src/public/translations/es/translation.json
=> i18n: Complete Spanish translation again

.github/workflows/main-docker.yml
Ahhhh, the joys of Docker....
Example run with these changes: https://github.com/perfectra1n/Notes/actions/runs/10835247772
Fixes: https://github.com/TriliumNext/Notes/actions/runs/10835024797/job/30065735116
=> Force `github.repository_owner` to lowercase

.github/workflows/main-docker.yml
I wiped it off and cheered it up, so it should be ready to go now.
=> Picking up the backslash that I dropped

src/public/app/widgets/buttons/global_menu.js
Fix strange underline for zoom button
=>  Fix strange underline for zoom button

src/public/app/widgets/floating_buttons/floating_buttons.js, src/public/app/widgets/floating_buttons/hide_floating_buttons_button.js, src/public/translations/en/translation.json
Change close button to collapsed
=> Floating buttons can be displayed again after being closed

src/services/search/expressions/order_by_and_limit.ts
Fix for https://github.com/TriliumNext/Notes/issues/441
=> Fixes issue #441: Dates were not parsed on sorting

src/public/translations/fr/translation.json, src/routes/api/options.ts, translations/fr/server.json
Major overhaul of french translation. Corrections & Consistency. Polished state !
I revised the (poor..) algorithmic translation I used as a draft in the first stage. I think I managed to have a consistent translation. Ready for a nightly build to test it ! 
Please, if any french users are here, I'd really like some feedback to improve it.
=> i18n : Add fr translation (2/2)

src/public/translations/es/translation.json, translations/es/server.json
Another weekend another Spanish translation update.
=> i18n: Update Spanish translations

Dockerfile, Dockerfile.alpine
Utilized build steps, and after lots of tweaks - it appears the container is 1/2 the size or even smaller.
You can view the build of the Dockerfile and Dockerfile.alpine [here](https://github.com/perfectra1n/Notes/actions/runs/11690274634) in my fork.
You can try the containers out for yourself here:
- [amd64](https://hub.docker.com/layers/perfectra1n/notes/develop/images/sha256-0ab9749bcbd3b565e2bb99fa11f209c1cd3dd05af8b84d5ff68e27747019c5a8?context=repo) (alpine)
- [arm64](https://hub.docker.com/layers/perfectra1n/notes/develop/images/sha256-dcfc1387d31821ee98f0520dcec7a5159bbeaa58d027ca409a2a41fc5d00cfe4?context=repo) (debian)
- [arm/v7](https://hub.docker.com/layers/perfectra1n/notes/develop/images/sha256-46728f4911030f47966db00af982429604bd921bfbb3235b68ad14815cfc5b4c?context=repo) …
=> Make the container smaller

src/public/translations/es/translation.json
=> i18n: Update Spanish translations for stable release

.github/workflows/renovate.yaml, renovate.json
This adds Renovate as our automatic dependency PR opener, and the JSON configuration file required for it.
=> Add renovate GitHub Action and JSON config

src/public/app/widgets/note_tree.js, src/public/stylesheets/theme-next/shell.css
=> Style Next: Restyle the tree settings popup

src/public/app/widgets/dialogs/recent_changes.js, src/public/stylesheets/style.css, src/public/stylesheets/theme-next.css, src/public/stylesheets/theme-next/shell.css
- The list items are now clickable across their entire width.
- Deleted notes are marked using striketrough text.
=> Style Next: Improve the styling of the "Recent Changes" list

docker-compose.yml
See #766 for more info
closes #766
=> chore(docker-compose): add remark about UFW issues

src/public/app/widgets/dialogs/about.js, src/public/app/widgets/dialogs/clone_to.js, src/public/app/widgets/dialogs/confirm.js, src/public/app/widgets/dialogs/delete_notes.js, src/public/app/widgets/dialogs/include_note.js, src/public/app/widgets/dialogs/jump_to_note.js, src/public/app/widgets/dialogs/markdown_import.js, src/public/app/widgets/dialogs/move_to.js, src/public/app/widgets/dialogs/note_type_chooser.js, src/public/app/widgets/dialogs/password_not_set.js, src/public/app/widgets/dialogs/prompt.js, src/public/app/widgets/dialogs/recent_changes.js, src/public/app/widgets/dialogs/revisions.js, src/public/app/widgets/dialogs/sort_child_notes.js, src/public/app/widgets/dialogs/upload_attachments.js, src/public/translations/en/translation.json
Hi,
Sorry for the many commits, it made it easier for me to track my changes - feel free to squash these together into one.
Closes #794
=> i18n: localize hardcoded English aria-labels

src/views/login.ejs
Hi,
this PR is aiming to simplify the JS part of the login view
=> refactor(view/login): simplify JS

src/views/login.ejs, translations/en/server.json
Hi,
this PR tries to improve the look of the Login view, by doing some minimal changes
Before
After
=> style(views/login): add Trilium icon and improve style

.github/workflows/main.yml, bin/build-server.sh
You can see working build here in my fork:
https://github.com/perfectra1n/Notes/actions/runs/12836541899/job/35798347703#step:5:556
=> Update build-server.sh and GitHub Actions to build ARM server

src/services/import/markdown.ts, src/services/import/mime_type_definitions.ts
Hi,
as discussed in #1010 – quick & dirty fix by copying over the file into the server side of things Comment added to both files, about deduplication in the future
more info can be found in said bug report
fixes #1010
=> fix: fix server build not running due to missing file

package-lock.json
fixes two "medium severity" vulnerabilities
=> fix(deps): run npm audit fix

.github/ISSUE_TEMPLATE/task.yml
Hi
this PR adds a new Issue Template for easily creating "internal" Tasks for Development and such.
=> chore(issue_templates): add simple Task template

forge.config.cjs
Hi,
just a small PR to make the electron forge config file a bit simpler.
=> refactor: electron forge config

src/public/app/widgets/type_widgets/protected_session.js
Hi,
this PR sets autofocus to the input element and also fixes the explicit input->label association.
=> feat/fix(protected_session): input improvements

package-lock.json, package.json
Hi,
I don't see any usage of jasmine anymore: Seems I forgot to remove it from package.json, when I added Vitest previously
=> chore(deps): remove unused jasmine

src/routes/login.ts
Hi,
this PR aims to simplify the login function.
It also gets rid of the deprecated usage of `expires` – setting `maxAge` to undefined is the preferred way and works the same.
https://github.com/expressjs/session/blob/4930de729107448e4b34b5bd39f138f71f1561f6/README.md?plain=1#L70
You can check this by checking the cookie that is set:
When you check "Remember me" it will create a cookie that will expire in 3 weeks.
```
Set-Cookie
trilium.sid=s%3A81Fxao2ShPyOoIhthErnu6rIN6B3eDe0.g9DVhz3LN3s0VhUcSyx1vgZzWqRocxnxxrSLyHFSgZQ; Path=/; Expires=Tue, 04 Mar 2025 07:11:46 GMT; HttpOnly
```
When you login with an unchecked "Remember me" it will create a cookie that expires when your browser session ends (because neither Expires, nor maxAge is being set)
```
Set-Cookie …
```
=> refactor(routes/login): simplify login function and get rid of deprecated usage of expires

bin/generate-openapi.js, package-lock.json, package.json, src/routes/api/app_info.ts, src/routes/api/login.ts, src/routes/api/setup.ts
As discussed in #1176
See the result here https://fliegendewurst.eu/tmp/trilium-openapi/
Once it is a bit more complete it could be added to one of the doc sites. (Just requires serving a directory of files, no server logic required.)
=> Automated OpenAPI spec generation

bin/generate-openapi.js, src/routes/api/app_info.ts, src/routes/api/branches.ts, src/routes/api/notes.ts, src/routes/api/sync.ts, src/routes/api/tree.ts
Live at https://fliegendewurst.eu/tmp/trilium-openapi/
Documented APIs are now sufficient to build a basic sync client (in fact `push` / `pull` are all I use in my Android app), or directly fetch some data.
We could now consider adding it to https://github.com/TriliumNext/Notes/blob/develop/src/routes/api_docs.ts (I am wondering how that function works anyhow, it seems to be passed an `Application` when it wants a `Router`. And I don't know how to find the served docs.)
=> More OpenAPI docs

src/public/app/widgets/view_widgets/calendar_view.ts
Follow-up of https://github.com/TriliumNext/Notes/pull/1213
=> feat(view/calendar): support coloring

src/public/app/widgets/sync_status.ts
Hi,
this PR ports the sync_status.js file to TS.
I've added two Type Related TODO remarks as well for future consideration
=> chore(ts): port sync_status.ts

src/routes/login.ts
Hi,
this PR fixes #1285 
(and sorry for sneaking in the refactor commit 1a0c35f43d960adc7b70a0c084e7d5f66311ccda)
=> fix: EJS crash after failed login

src/public/app/widgets/buttons/calendar.ts, src/public/app/widgets/buttons/history_navigation.ts
- port calender to ts
- optimize month selector behavior
- port history navigation, remove redundance
=> porting js

src/public/app/widgets/type_widgets/read_only_code.ts
Placeholder PR, to avoid any duplicate work :-)
should be ready this evening :-)
=> chore(ts): start porting read_only_code

src/public/translations/es/translation.json, translations/es/server.json
Completed and fixed some typos.
=> chore(i18n): update Spanish translation

bin/tpl/trilium-no-cert-check.bat, bin/tpl/trilium-portable.bat, bin/tpl/trilium-safe-mode.bat
Fixes missing quotes in the `bat` files.
=> Fixes missing quotes in the `bat` files.

README.md
I hope the wording is okay. The app is now fairly stable and supports most features you'd need on a phone.
=> README.md: TriliumDroid link, documentation update

src/public/stylesheets/theme-next/forms.css
Should use --link-color as the link color to keep theme compatibility.
=> Use --link-color as the color of links

src/routes/login.ts
=> hotfix(auth): fix TOTP validation bypass issue

src/routes/login.ts
=> Fix "Cannot set headers after they are sent" error in logout function

src/public/app/widgets/type_widgets/geo_map.ts, webpack.config.ts
fixes regression that @eliandoran noticed (thanks!):
https://github.com/TriliumNext/Notes/pull/1610#issuecomment-2776509430
=> fix(geo_map): fix leaflet asset copying/loading

src/routes/login.ts
=> fix(login): fix regression that removed support for setting custom cookieMaxAge
